##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

httpclient:
  connectTimeout: 20000
  requestTimeout: 20000
  socketTimeout: 30000
  defaultMaxPerRoute: 100
  maxTotalConnections: 300
  defaultKeepAliveTimeMillis: 20000
  closeIdleConnectionWaitTimeSecs: 30

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: D:/logs/app.log
