server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot_sso_demo?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  oauth2:
      resource:
        jwt:
          keyUri: http://localhost/oauth/token_key


