##########################################################
##################  所有profile共有的配置  #################
##########################################################


###################  spring配置  ###################
spring:
  profiles:
    active: dev

server:
  port: 8092

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: D:/logs/app.log
