server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: example.com
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
