spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    ## druid连接池配置 ##
    initialSize: 5
    maxActive: 100
    minIdle: 5
    maxWait: 60000
    validationQuery: select 1
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: mergeStat
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
logging:
  config: classpath:config/logback.xml

## 项目自定义的配置 ##
appConfigLocation: classpath:/config/appload.properties