server:
  port: 8080
  servlet:
    context-path: /
qiniu:
  ## 此处填写你自己的七牛云 access key
  accessKey: xxx
  ## 此处填写你自己的七牛云 secret key
  secretKey: yyy
  ## 此处填写你自己的七牛云 bucket
  bucket: hangzhou
  ## 此处填写你自己的七牛云 域名
  prefix: hi
spring:
  servlet:
    multipart:
      enabled: true
      # 本地上传路径
      location: D:/upload
      file-size-threshold: 5MB
      max-file-size: 20MB
