server:
  port: 8081

#logging:
#  level:
##    com.base.voice.mapper: debug
#    com.base.voice.autodialer.mapper: debug



weixin:
  app-id: wxd8547a419105c817
  app-secret: c16f43f4e602ee1ddfcc64d01f766fbe
  token: aliang

  media:
    voice:
      template: D:\weixinpath\template\
      path: D:\weixinpath\voice\
      reply-path: D:\weixinpath\voice_reply\

#MYBATIS
mybatis:
  type-aliases-package: com.base.voice.entity,com.base.voice.autodialer.entity
  mapper-locations: classpath*:/mapper/*/*Mapper.xml,classpath*:/mapper/*Mapper.xml

  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-fetch-size: 100
    default-statement-timeout: 30

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/wx_data?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root123
    url: jdbc:mysql://192.168.1.82:3306/autodialer?useUnicode=true&characterEncoding=UTF-8
    username: vector
    password: vector
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
    connectionProperties:
      druid.stat.mergeSql: true
      druid.stat.slowSqlMillis: 5000
  redis:
    database: 1
    host: localhost
    port: 6379
    password:
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0
#      timeout: 500

robot:
  notify-url: http://192.168.22.2:8081/robot/callNotify
  # 最好为插卡数-1
  maximumcall: 2
  is-need-upload-file: false

  conversion:
#    v1:
#      voice-url: http://192.168.1.31:9840/v1/speech/chart
#      text-url: http://192.168.1.31:9840/v1/text/chart
    v2:
      voice-url: http://192.168.216.216:9841/v2/speech/chat
      text-url: http://192.168.216.216:9841/v2/text/chart
    v3:
      text-url: http://192.168.216.216:9844/v3/text/chat
      voice-url: http://192.168.216.216:9843/v3/speech/chat
  robot-file-path:
    # 0 随机 ， 1 男声 ， 2 女声 , 3 盖茨比
    mode: 1
    male: /var/smartivr/voice/male
    female: /var/smartivr/voice/female
    other: /var/smartivr/voice/gcb
  # 单位毫秒
  block-asr-duration: 4000


  oss:
   bucket: bazatest
   path: robotrecordfiletest



