##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://xiongneng:123456@localhost:27017/test

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: D:/logs/app.log
