spring:
  data:
    mongodb:
      host: example.com
      port: 27017
      database: admin
      username: mongo-admin
      password: mongo-password
logging:
  level:
    org.springframework.data.mongodb.core: debug
