##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 8092

###################  spring配置  ###################
spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: E:/logs/app.log

---

#####################################################################
########################  测试环境profile  ##########################
#####################################################################

spring:
  profiles: test

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /var/logs/app.log
